platform :ios, '13.0'
use_frameworks!

target 'GreenTravel' do
  pod 'SDWebImage'
  pod 'Mapbox-iOS-SDK', '~> 6.0.0'
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Performance'
end
